---
id: c771e3e4-5807-4b25-97ad-5aba2b6bc8c2
registrations:
  - validity:
      - input:
          class:
            id: 8e80de8b-4c8c-42ca-8ddd-cec816a955fa
            name: Process Configuration
          process:
            id: 882247a3-ee84-4b39-bf99-05fecd0e9af0
            name: STSOrgSync Prod
          integrationSpec:
            id: 02f69145-59db-480f-883c-40fa7bd4f962
            name: STSSOrgSync Prod Extraction
        from: 2018-01-01T00:00:00.000Z
...
